Fix AdControll, AdService. Fix AuthService and config
HeimTN/SKYPRO_likeAvito pull request #11
Opened 2023-12-20 08:17 UTC by HeimTN

2023-12-21 18:28 UTC, 1237633 requested changes

2023-12-21 18:28 UTC, 1237633 commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                "SELECT login, password, enabled FROM users WHERE login = ?");
Ты же говорил убрать логин из юзера. Я думал, уже тогда оставим ТОЛЬКО почту и везде будем ее юзать. Тогда оставляю?

2023-12-22 04:15 UTC, HeimTN commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                "SELECT login, password, enabled FROM users WHERE login = ?");
Ну ты же уже по логину настроил индексацию, проще email убрать и прокинуть в мапере c логина на емеил

2023-12-22 04:16 UTC, HeimTN commented on src/main/java/ru/skypro/homework/config/WebSecurityConfig.java
> +                "SELECT login, password, enabled FROM users WHERE login = ?");
Я сделаю, забей, лучше сервисы пропиши)

2023-12-25 15:03 UTC, merged