DTO class and controller for Comment were added.
HeimTN/SKYPRO_likeAvito pull request #4
Opened 2023-12-09 18:06 UTC by AnnBelousova

DTO class and controller for Comment were added.

2023-12-10 10:00 UTC, 1237633 requested changes

2023-12-10 20:10 UTC, AnnBelousova commented on src/main/java/ru/skypro/homework/dto/Comment.java
изменила id на pk

2023-12-10 20:10 UTC, AnnBelousova commented on src/main/java/ru/skypro/homework/dto/Comment.java
> +    private LocalDateTime createdAt;
изменила на long.

2023-12-11 11:00 UTC, HeimTN approved these changes

2023-12-11 15:50 UTC, merged